name: Tests
on: push
jobs:
  build:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 13]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: stefanoeb/eslint-action@1.0.2
      - name: Install MongoDB
        run: sudo apt install -y mongodb
      - name: Install Modules
        run: npm ci
      - name: Create Directories
        run: mkdir crypto files && sudo mkdir /data/db -p
      - name: Generate Salt
        run: cd crypto && openssl rand -out secret.txt -base64 512
      - name: Generate Certificate
        run: cd crypto && openssl req -newkey rsa:2048 -nodes -x509 -subj "/CN=127.0.0.1" -addext "subjectAltName = IP:127.0.0.1" -keyout key.pem -out cert.pem
      - name: Test
        run: sudo npm test
      - name: Clean Up
        run: sudo rm -rf node_modules