name: Tests
on: push
jobs:
  build:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [13, 14]
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: stefanoeb/eslint-action@1.0.2
        name: ESLint
      - name: Install MongoDB
        run: sudo apt install -y mongodb
      - name: Install Modules
        run: sudo npm ci
      - name: Create Directories
        run: mkdir files && sudo mkdir /data/db -p
      - name: Generate Salt
        run: cd config && openssl rand -out secret.txt -base64 512
      - name: Generate Certificate
        run: cd config && openssl req -newkey rsa:2048 -nodes -x509 -subj "/CN=127.0.0.1" -addext "subjectAltName = IP:127.0.0.1" -keyout key.pem -out cert.cer
      - uses: paambaati/codeclimate-action@v2.6.0
        name: Test
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: sudo npm run coverage